apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: prod-gateway
  namespace: prod
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - prod.adarsh-jain-ecom.gt.tc
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prod-vs
  namespace: prod
spec:
  hosts:
    - prod.adarsh-jain-ecom.gt.tc
  gateways:
    - prod-gateway
  http:
    - match:
      - uri:
          prefix: /student
      - uri:
          prefix: /teacher
      - uri:
          prefix: /addstudent
      - uri:
          prefix: /addteacher
      route:
      - destination:
          host: backend.prod.svc.cluster.local
          port:
            number: 3500

    # ---- Frontend LAST ----
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend.prod.svc.cluster.local
            port:
              number: 80
