apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: prod
type: Opaque
stringData:
  DB_HOST: ptmdb.c47akookwd22.us-east-1.rds.amazonaws.com
  DB_USER: mysqluser
  DB_PASSWORD: password1
  DB_NAME: ptmdb
  DB_PORT: "3306"
