apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: prod
type: Opaque
stringData:
  DB_HOST: ptm.c47akookwd22.us-east-1.rds.amazonaws.com
  DB_USER: admin
  DB_PASSWORD: password
  DB_NAME: ptm
